/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdministracionGUI.java
 *
 * Created on 05-sep-2014, 19:27:35
 */
package tesis.ventanas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tesis.clasificacion.nb.ControladoraClasificadorNB;

/**
 *
 * @author tebs
 */
public class AdministracionGUI extends javax.swing.JFrame {

    private EtiquetadoManualGUI etiquetadoManualGUI;
    private PreProcesamientoGUI preprocesamientoGUI;
    private ClasificacionGUI clasificacionGUI;
    private ValidacionManualGUI validacionManualGUI;
    private ControladoraClasificadorNB controladoraNB;

    /**
     * Creates new form AdministracionGUI
     */
    public AdministracionGUI() {
        initComponents();
        controladoraNB = new ControladoraClasificadorNB();
        etiquetadoManualGUI = new EtiquetadoManualGUI(controladoraNB);
        preprocesamientoGUI = new PreProcesamientoGUI(controladoraNB);
        clasificacionGUI = new ClasificacionGUI(controladoraNB);
        validacionManualGUI = new ValidacionManualGUI(controladoraNB);
        
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("Twitter-Shipping-Box-32.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:. Clasificador Tweets .:.");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Etapas");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Etiquetado Manual...");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Preprocesamiento...");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Entrenar y Clasificar...");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        jMenuItem1.setText("Validar...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem1);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Manual...");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de...");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1139, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        try {
            this.controladoraNB.getConexion().cerrarConexion();
            System.exit(0);
        } catch (SQLException ex) {
            Logger.getLogger(AdministracionGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        int x = (desktopPane.getWidth() / 2) - etiquetadoManualGUI.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - etiquetadoManualGUI.getHeight() / 2;
        if (etiquetadoManualGUI.isShowing()) {
            etiquetadoManualGUI.setLocation(x, y);
        } else {
            desktopPane.add(etiquetadoManualGUI); //Tira excepcion UNA vez, despues de cerrar la ventana anterior
            etiquetadoManualGUI.setLocation(x, y);
            etiquetadoManualGUI.show();
        }
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int x = (desktopPane.getWidth() / 2) - validacionManualGUI.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - validacionManualGUI.getHeight() / 2;
        if (validacionManualGUI.isShowing()) {
            validacionManualGUI.setLocation(x, y);
        } else {
            desktopPane.add(validacionManualGUI); //Tira excepcion UNA vez, despues de cerrar la ventana anterior
            validacionManualGUI.setLocation(x, y);
            validacionManualGUI.show();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        int x = (desktopPane.getWidth() / 2) - preprocesamientoGUI.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - preprocesamientoGUI.getHeight() / 2;
        if (preprocesamientoGUI.isShowing()) {
            preprocesamientoGUI.setLocation(x, y);
        } else {
            desktopPane.add(preprocesamientoGUI); //Tira excepcion UNA vez, despues de cerrar la ventana anterior
            preprocesamientoGUI.setLocation(x, y);
            preprocesamientoGUI.show();
        }
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        int x = (desktopPane.getWidth() / 2) - clasificacionGUI.getWidth() / 2;
        int y = (desktopPane.getHeight() / 2) - clasificacionGUI.getHeight() / 2;
        if (clasificacionGUI.isShowing()) {
            clasificacionGUI.setLocation(x, y);
        } else {
            desktopPane.add(clasificacionGUI); //Tira excepcion UNA vez, despues de cerrar la ventana anterior
            clasificacionGUI.setLocation(x, y);
            clasificacionGUI.show();
        }
    }//GEN-LAST:event_deleteMenuItemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
