/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EtiquetadoManual.java
 *
 * Created on 08-abr-2014, 19:11:22
 */
package tesis.ventanas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tesis.clasificacion.manual.Recolector;
import tesis.clasificacion.nb.ControladoraClasificadorNB;
import tesis.util.Tweet;

/**
 *
 * @author tebs
 */
public class EtiquetadoManualGUI extends javax.swing.JInternalFrame {

    private Tweet tweet;
    private ControladoraClasificadorNB controladora;
    private boolean[] etiquetas = {false, false, false, false, false, false, false};
    private boolean[] polaridad = {false, false, false};
    private Integer contar = 0;
    private Integer contarEliminados = 0;
    private String totalesEtiquetas[];

    /**
     * Creates new form EtiquetadoManual
     */
    public EtiquetadoManualGUI(ControladoraClasificadorNB controladora) {
        try {
            initComponents();
            this.controladora = controladora;
            this.iniciar();
            totalesEtiquetas = controladora.getRecolector().contarEtiquetados();
            this.contadorBsAs.setText(totalesEtiquetas[0]);
            this.contadorCal.setText(totalesEtiquetas[1]);
            this.contadorCat.setText(totalesEtiquetas[2]);
            this.contadorSalt.setText(totalesEtiquetas[3]);
            this.contadorTdf.setText(totalesEtiquetas[4]);
            this.contadorNg.setText(totalesEtiquetas[5]);
            this.contadorTot.setText(totalesEtiquetas[6]);
            this.contadorTotGral.setText(totalesEtiquetas[7]);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clasePanel = new javax.swing.JPanel();
        bs = new javax.swing.JCheckBox();
        ng = new javax.swing.JCheckBox();
        tf = new javax.swing.JCheckBox();
        cal = new javax.swing.JCheckBox();
        indefinido = new javax.swing.JCheckBox();
        sal = new javax.swing.JCheckBox();
        cat = new javax.swing.JCheckBox();
        polaridadPanel = new javax.swing.JPanel();
        pos = new javax.swing.JCheckBox();
        neg = new javax.swing.JCheckBox();
        neu = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        etiquetar = new javax.swing.JButton();
        saltar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idTweet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tweetsArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        fechaUtc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fechaLocal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        timezone = new javax.swing.JTextField();
        contadorNg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contadorCat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contadorCal = new javax.swing.JLabel();
        contadorTdf = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        contadorSalt = new javax.swing.JLabel();
        contadorBsAs = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        contadorTot = new javax.swing.JLabel();
        contadorTotGral = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setForeground(java.awt.Color.white);
        setTitle(".:. Clasificador Tweets .:.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Twitter-Shipping-Box-32.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Etiquetado Manual"));

        clasePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));
        clasePanel.setEnabled(false);

        bs.setText("BS");
        bs.setEnabled(false);

        ng.setText("NG");
        ng.setEnabled(false);
        ng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngActionPerformed(evt);
            }
        });

        tf.setText("TF");
        tf.setEnabled(false);

        cal.setText("CAL");
        cal.setEnabled(false);

        indefinido.setText("?");
        indefinido.setEnabled(false);
        indefinido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indefinidoActionPerformed(evt);
            }
        });

        sal.setText("SAL");
        sal.setEnabled(false);

        cat.setText("CAT");
        cat.setEnabled(false);

        javax.swing.GroupLayout clasePanelLayout = new javax.swing.GroupLayout(clasePanel);
        clasePanel.setLayout(clasePanelLayout);
        clasePanelLayout.setHorizontalGroup(
            clasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clasePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indefinido)
                .addContainerGap())
        );
        clasePanelLayout.setVerticalGroup(
            clasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clasePanelLayout.createSequentialGroup()
                .addGroup(clasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bs)
                    .addComponent(cal)
                    .addComponent(cat)
                    .addComponent(sal)
                    .addComponent(ng)
                    .addComponent(indefinido)
                    .addComponent(tf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        polaridadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sentimiento"));
        polaridadPanel.setEnabled(false);

        pos.setEnabled(false);
        pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posActionPerformed(evt);
            }
        });

        neg.setEnabled(false);
        neg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negActionPerformed(evt);
            }
        });

        neu.setEnabled(false);
        neu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/muhaha-32.png"))); // NOI18N
        jLabel16.setToolTipText("Positivo");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/sarcastic sadness-32.png"))); // NOI18N
        jLabel17.setToolTipText("Negativo");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/huh-where-32.png"))); // NOI18N
        jLabel19.setToolTipText("Neutro");

        javax.swing.GroupLayout polaridadPanelLayout = new javax.swing.GroupLayout(polaridadPanel);
        polaridadPanel.setLayout(polaridadPanelLayout);
        polaridadPanelLayout.setHorizontalGroup(
            polaridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, polaridadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(neu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        polaridadPanelLayout.setVerticalGroup(
            polaridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(polaridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel16)
                .addGroup(polaridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(polaridadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(neg, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pos)
                        .addComponent(neu))))
            .addComponent(jLabel19)
        );

        etiquetar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Tag-Blue-32.png"))); // NOI18N
        etiquetar.setToolTipText("Etiquetar");
        etiquetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiquetarActionPerformed(evt);
            }
        });

        saltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Undo-32.png"))); // NOI18N
        saltar.setToolTipText("Saltar");
        saltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saltarActionPerformed(evt);
            }
        });

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Delete-32.png"))); // NOI18N
        eliminar.setToolTipText("Borrar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Close-32.png"))); // NOI18N
        jButton1.setToolTipText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        idTweet.setEditable(false);

        jLabel8.setText("@");

        username.setEditable(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        tweetsArea.setColumns(120);
        tweetsArea.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        tweetsArea.setForeground(new java.awt.Color(0, 0, 153));
        tweetsArea.setRows(1);
        tweetsArea.setAutoscrolls(false);
        tweetsArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tweetsAreaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tweetsArea);

        jLabel9.setText("Fecha UTC:");

        fechaUtc.setEditable(false);

        jLabel10.setText("Fecha Loc:");

        fechaLocal.setEditable(false);

        jLabel11.setText("Locación:");

        location.setEditable(false);

        jLabel12.setText("Timezone:");

        timezone.setEditable(false);

        contadorNg.setText("xxxx");

        jLabel2.setText("Ninguno:");

        contadorCat.setText("xxxx");

        jLabel1.setText("Cataratas:");

        jLabel3.setText("Total etiquetados:");

        contadorCal.setText("xxxx");

        contadorTdf.setText("xxxx");

        jLabel18.setText("T. del Fuego:");

        contadorSalt.setText("xxxx");

        contadorBsAs.setText("xxxx");

        jLabel13.setText("Bs. As.: ");

        jLabel15.setText("Salta:");

        jLabel14.setText("Calafate:");

        contadorTot.setText("xxxx");

        contadorTotGral.setText("xxxxxx");

        jLabel4.setText("Total General:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTweet, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(2, 2, 2)
                                .addComponent(contadorBsAs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contadorCal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contadorCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contadorSalt)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel18)
                                .addGap(6, 6, 6)
                                .addComponent(contadorTdf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contadorNg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contadorTot, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addGap(221, 221, 221)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contadorTotGral))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(fechaUtc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(timezone))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(clasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(polaridadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(saltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polaridadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(idTweet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fechaUtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(fechaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timezone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contadorTotGral)
                    .addComponent(jLabel1)
                    .addComponent(contadorCat)
                    .addComponent(jLabel15)
                    .addComponent(contadorSalt)
                    .addComponent(jLabel18)
                    .addComponent(contadorTdf)
                    .addComponent(jLabel13)
                    .addComponent(contadorBsAs)
                    .addComponent(jLabel14)
                    .addComponent(contadorCal)
                    .addComponent(jLabel2)
                    .addComponent(contadorNg)
                    .addComponent(jLabel3)
                    .addComponent(contadorTot))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tweetsAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tweetsAreaAncestorAdded
   }//GEN-LAST:event_tweetsAreaAncestorAdded

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            controladora.getRecolector().eliminarTweet("tweets", this.tweet.getId().toString());
            contarEliminados++;
            //this.valEliminados.setText(contarEliminados.toString());
            this.tweet = controladora.getRecolector().leerTweets("tweets");
            this.tweetsArea.setText(tweet.getStatus());
            this.idTweet.setText(this.tweet.getId().toString());
            this.username.setText(tweet.getUsername());
            this.fechaLocal.setText(tweet.getLocaldate());
            this.fechaUtc.setText(tweet.getUtcdate());
            this.location.setText(tweet.getLocation());
            this.timezone.setText(tweet.getTimezone());
            this.contadorTotGral.setText(controladora.getRecolector().contarTotal());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void saltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltarActionPerformed
        try {
            this.tweet = controladora.getRecolector().leerTweets("tweets");
            this.tweetsArea.setText(tweet.getStatus());
            this.idTweet.setText(this.tweet.getId().toString());
            this.username.setText(tweet.getUsername());
            this.fechaLocal.setText(tweet.getLocaldate());
            this.fechaUtc.setText(tweet.getUtcdate());
            this.location.setText(tweet.getLocation());
            this.timezone.setText(tweet.getTimezone());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_saltarActionPerformed

    private void etiquetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiquetarActionPerformed
        try {
            etiquetas[0] = this.bs.isSelected();
            etiquetas[1] = this.cal.isSelected();
            etiquetas[2] = this.cat.isSelected();
            etiquetas[3] = this.sal.isSelected();
            etiquetas[4] = this.tf.isSelected();
            etiquetas[5] = this.ng.isSelected();
            etiquetas[6] = this.indefinido.isSelected();
            polaridad[0] = this.pos.isSelected();
            polaridad[1] = this.neg.isSelected();
            polaridad[2] = this.neu.isSelected();
            this.tweet.setStatus(this.tweetsArea.getText());
            this.idTweet.setText(this.tweet.getId().toString());
            controladora.getRecolector().etiquetarTweets("tweets", this.tweet, this.etiquetas, this.polaridad, "2");
            totalesEtiquetas = controladora.getRecolector().contarEtiquetados();
            this.contadorBsAs.setText(totalesEtiquetas[0]);
            this.contadorCal.setText(totalesEtiquetas[1]);
            this.contadorCat.setText(totalesEtiquetas[2]);
            this.contadorSalt.setText(totalesEtiquetas[3]);
            this.contadorTdf.setText(totalesEtiquetas[4]);
            this.contadorNg.setText(totalesEtiquetas[5]);
            this.contadorTot.setText(totalesEtiquetas[6]);
            contar++;
            //this.valClasificados.setText(contar.toString());
            this.bs.setSelected(false);
            this.cal.setSelected(false);
            this.cat.setSelected(false);
            this.sal.setSelected(false);
            this.tf.setSelected(false);
            this.ng.setSelected(false);
            this.indefinido.setSelected(false);
            this.pos.setSelected(false);
            this.neg.setSelected(false);
            this.neu.setSelected(false);
            this.bs.setEnabled(true);
            this.cal.setEnabled(true);
            this.cat.setEnabled(true);
            this.sal.setEnabled(true);
            this.tf.setEnabled(true);
            this.ng.setEnabled(true);
            this.indefinido.setEnabled(true);
            this.pos.setEnabled(true);
            this.neg.setEnabled(true);
            this.neu.setEnabled(true);
            this.polaridadPanel.setEnabled(true);
            this.tweet = controladora.getRecolector().leerTweets("tweets");
            this.username.setText(tweet.getUsername());
            this.fechaLocal.setText(tweet.getLocaldate());
            this.fechaUtc.setText(tweet.getUtcdate());
            this.location.setText(tweet.getLocation());
            this.timezone.setText(tweet.getTimezone());
            this.tweetsArea.setText(tweet.getStatus());
        } catch (Exception ex) {
            Logger.getLogger(EtiquetadoManualGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_etiquetarActionPerformed

    private void neuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuActionPerformed
        if (this.neg.isEnabled()) {
            this.neg.setEnabled(false);
            this.pos.setEnabled(false);
        } else {
            this.neg.setEnabled(true);
            this.pos.setEnabled(true);
        }
    }//GEN-LAST:event_neuActionPerformed

    private void negActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negActionPerformed
        if (this.pos.isEnabled()) {
            this.pos.setEnabled(false);
            this.neu.setEnabled(false);
        } else {
            this.pos.setEnabled(true);
            this.neu.setEnabled(true);
        }
    }//GEN-LAST:event_negActionPerformed

    private void posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posActionPerformed
        if (this.neg.isEnabled()) {
            this.neg.setEnabled(false);
            this.neu.setEnabled(false);
        } else {
            this.neg.setEnabled(true);
            this.neu.setEnabled(true);
        }
    }//GEN-LAST:event_posActionPerformed

    private void indefinidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indefinidoActionPerformed
        if (this.bs.isEnabled()) {
            this.bs.setEnabled(false);
            this.cal.setEnabled(false);
            this.cat.setEnabled(false);
            this.sal.setEnabled(false);
            this.tf.setEnabled(false);
            this.ng.setEnabled(false);
        } else {
            this.bs.setEnabled(true);
            this.cal.setEnabled(true);
            this.cat.setEnabled(true);
            this.sal.setEnabled(true);
            this.tf.setEnabled(true);
            this.ng.setEnabled(true);
        }
        this.bs.setSelected(false);
        this.cal.setSelected(false);
        this.cat.setSelected(false);
        this.sal.setSelected(false);
        this.tf.setSelected(false);
        this.ng.setSelected(false);
    }//GEN-LAST:event_indefinidoActionPerformed

    private void ngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngActionPerformed
        if (this.bs.isEnabled()) {
            this.bs.setEnabled(false);
            this.cal.setEnabled(false);
            this.cat.setEnabled(false);
            this.sal.setEnabled(false);
            this.tf.setEnabled(false);
            this.indefinido.setEnabled(false);
        } else {
            this.bs.setEnabled(true);
            this.cal.setEnabled(true);
            this.cat.setEnabled(true);
            this.sal.setEnabled(true);
            this.tf.setEnabled(true);
            this.indefinido.setEnabled(true);
        }
        this.bs.setSelected(false);
        this.cal.setSelected(false);
        this.cat.setSelected(false);
        this.sal.setSelected(false);
        this.tf.setSelected(false);
        this.indefinido.setSelected(false);
        if (this.polaridadPanel.isEnabled()) {
            this.polaridadPanel.setEnabled(false);
            this.pos.setEnabled(false);
            this.neg.setEnabled(false);
            this.neu.setEnabled(false);
        } else {
            this.polaridadPanel.setEnabled(true);
            this.pos.setEnabled(true);
            this.neg.setEnabled(true);
            this.neu.setEnabled(true);
        }
    }//GEN-LAST:event_ngActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bs;
    private javax.swing.JCheckBox cal;
    private javax.swing.JCheckBox cat;
    private javax.swing.JPanel clasePanel;
    private javax.swing.JLabel contadorBsAs;
    private javax.swing.JLabel contadorCal;
    private javax.swing.JLabel contadorCat;
    private javax.swing.JLabel contadorNg;
    private javax.swing.JLabel contadorSalt;
    private javax.swing.JLabel contadorTdf;
    private javax.swing.JLabel contadorTot;
    private javax.swing.JLabel contadorTotGral;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton etiquetar;
    private javax.swing.JTextField fechaLocal;
    private javax.swing.JTextField fechaUtc;
    private javax.swing.JTextField idTweet;
    private javax.swing.JCheckBox indefinido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JCheckBox neg;
    private javax.swing.JCheckBox neu;
    private javax.swing.JCheckBox ng;
    private javax.swing.JPanel polaridadPanel;
    private javax.swing.JCheckBox pos;
    private javax.swing.JCheckBox sal;
    private javax.swing.JButton saltar;
    private javax.swing.JCheckBox tf;
    private javax.swing.JTextField timezone;
    private javax.swing.JTextArea tweetsArea;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        try {
            this.bs.setEnabled(true);
            this.cal.setEnabled(true);
            this.cat.setEnabled(true);
            this.sal.setEnabled(true);
            this.tf.setEnabled(true);
            this.ng.setEnabled(true);
            this.indefinido.setEnabled(true);
            this.pos.setEnabled(true);
            this.neg.setEnabled(true);
            this.neu.setEnabled(true);
            this.clasePanel.setEnabled(true);
            this.polaridadPanel.setEnabled(true);
            this.tweet = controladora.getRecolector().leerTweets("tweets");
            this.tweetsArea.setText(tweet.getStatus());
            this.idTweet.setText(this.tweet.getId().toString());
            this.username.setText(tweet.getUsername());
            this.fechaLocal.setText(tweet.getLocaldate());
            this.fechaUtc.setText(tweet.getUtcdate());
            this.location.setText(tweet.getLocation());
            this.timezone.setText(tweet.getTimezone());
        } catch (Exception ex) {
            Logger.getLogger(EtiquetadoManualGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
