/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tesis.ventanas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import tesis.clasificacion.nb.ControladoraClasificadorNB;
import tesis.util.HiloPreprocesamiento;
import tesis.util.Tweet;

/**
 *
 * @author tebs
 */
public class PreProcesamientoGUI extends javax.swing.JInternalFrame {

    private ControladoraClasificadorNB controladora;
    private List<Tweet> listaTweetEntrenar;
    private List<Tweet> listaTweetClasificar;

    /**
     * Creates new form PreProcesamientoGUI
     */
    public PreProcesamientoGUI(ControladoraClasificadorNB controladoraNB) {
        initComponents();
        this.controladora = controladoraNB;
        this.listaTweetEntrenar = new ArrayList<>();
    }

    public List<Tweet> getListaTweetClasificar() {
        return listaTweetClasificar;
    }

    public void setListaTweetClasificar(List<Tweet> listaTweetClasificar) {
        this.listaTweetClasificar = listaTweetClasificar;
    }

    public List<Tweet> getListaTweetEntrenar() {
        return listaTweetEntrenar;
    }

    public void setListaTweetEntrenar(List<Tweet> listaTweetEntrenar) {
        this.listaTweetEntrenar = listaTweetEntrenar;
    }

    public ControladoraClasificadorNB getControladora() {
        return controladora;
    }

    public void setControladora(ControladoraClasificadorNB controladora) {
        this.controladora = controladora;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getContUrl() {
        return contUrl;
    }

    public void setContUrl(JLabel contUrl) {
        this.contUrl = contUrl;
    }

    public JLabel getContCarEsp() {
        return contCarEsp;
    }

    public void setContCarEsp(JLabel contCarEsp) {
        this.contCarEsp = contCarEsp;
    }

    public JLabel getContCasual() {
        return contCasual;
    }

    public void setContCasual(JLabel contCasual) {
        this.contCasual = contCasual;
    }

    public JLabel getContEmo() {
        return contEmo;
    }

    public void setContEmo(JLabel contEmo) {
        this.contEmo = contEmo;
    }


    public JLabel getContMencion() {
        return contMencion;
    }

    public void setContMencion(JLabel contMencion) {
        this.contMencion = contMencion;
    }

    public JLabel getContPalCla() {
        return contPalCla;
    }

    public void setContPalCla(JLabel contPalCla) {
        this.contPalCla = contPalCla;
    }

    public JLabel getContPocoFrec() {
        return contPocoFrec;
    }

    public void setContPocoFrec(JLabel contPocoFrec) {
        this.contPocoFrec = contPocoFrec;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        estadoLowerCasing = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        estadoURL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        estadoMenciones = new javax.swing.JLabel();
        estadoAcentos = new javax.swing.JLabel();
        estadoEmoticones = new javax.swing.JLabel();
        estadoCaracEsp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        estadoStopWord = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        estadoPalClave = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        estadoLenguajeCasual = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadoLematizador = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        estadoPalRara = new javax.swing.JLabel();
        fin = new javax.swing.JLabel();
        contUrl = new javax.swing.JLabel();
        contMencion = new javax.swing.JLabel();
        contEmo = new javax.swing.JLabel();
        contCarEsp = new javax.swing.JLabel();
        contPalCla = new javax.swing.JLabel();
        contCasual = new javax.swing.JLabel();
        contPocoFrec = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setTitle(".:. Clasificador Tweets .:.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Twitter-Shipping-Box-32.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel de Preprocesamiento"));

        jLabel1.setText("Lower Casing");

        estadoLowerCasing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Close-32.png"))); // NOI18N
        jButton1.setToolTipText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Broom-32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText(" URLs");

        estadoURL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jLabel3.setText("Menciones");

        jLabel4.setText("Acentos");

        jLabel5.setText("Emoticones");

        jLabel6.setText("Caracteres Especiales");

        estadoMenciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        estadoAcentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        estadoEmoticones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        estadoCaracEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jLabel7.setText("Stop Words");

        estadoStopWord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jLabel8.setText("Pal. Claves");

        estadoPalClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jLabel9.setText("Lenguajes Casuales");

        estadoLenguajeCasual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jLabel10.setText("Lematizador");

        estadoLematizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        jLabel11.setText("Pal. Poco Frecuentes");

        estadoPalRara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/inactivo.png"))); // NOI18N

        contUrl.setText("(0)");

        contMencion.setText("(0)");

        contEmo.setText("(0)");

        contCarEsp.setText("(0)");

        contPalCla.setText("(0)");

        contCasual.setText("(0)");

        contPocoFrec.setText("(0)");

        jLabel12.setText("Haga clic en");

        jLabel13.setText("para iniciar el preprocesamiento. Esto puede tardar varios minutos...");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tesis/ventanas/Broom-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(estadoAcentos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(estadoLematizador))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(estadoMenciones)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contMencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(54, 54, 54))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(estadoLowerCasing)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel1))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(estadoURL)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(contUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(67, 67, 67)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(estadoStopWord)
                                                .addComponent(estadoPalClave, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(estadoLenguajeCasual, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(estadoEmoticones)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contEmo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(estadoCaracEsp)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(estadoPalRara))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contCarEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(contPocoFrec)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(contPalCla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(26, 26, 26)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(contCasual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estadoLowerCasing, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(estadoStopWord, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(estadoPalClave)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(estadoLenguajeCasual)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(estadoLematizador))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel8)
                                                            .addComponent(contPalCla))
                                                        .addGap(29, 29, 29)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel9)
                                                            .addComponent(contCasual))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel10))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2)
                                                            .addComponent(contUrl))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(estadoPalRara)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel11)
                                                .addComponent(contPocoFrec)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(contMencion))
                                        .addGap(78, 78, 78)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(contEmo))
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(contCarEsp)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estadoURL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoMenciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoAcentos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoEmoticones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoCaracEsp))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Primero hago el preprocesamiento para los tweets de entrenamiento
        //Luego hago el preprocesamiento para los tweets de clasificacion
        System.out.println("PREPROCESAMIENTO PARA ENTRENAR");
        listaTweetEntrenar = this.getControladora().procesar("clase <> '' AND clase <> '7' order by random()", 0, this);
        this.controladora.setTweetsEntrenar(listaTweetEntrenar);
        System.out.println("PREPROCESAMIENTO PARA CLASIFICAR");
        HiloPreprocesamiento lowerCasing = new HiloPreprocesamiento(1, estadoLowerCasing, this);
        lowerCasing.start();
        while (lowerCasing.isAlive()) {
        }
        HiloPreprocesamiento urls = new HiloPreprocesamiento(2, estadoURL, this);
        urls.start();
        while (urls.isAlive()) {
        }
        HiloPreprocesamiento menciones = new HiloPreprocesamiento(3, estadoMenciones, this);
        menciones.start();
        while (menciones.isAlive()) {
        }
        HiloPreprocesamiento acentos = new HiloPreprocesamiento(4, estadoAcentos, this);
        acentos.start();
        while (acentos.isAlive()) {
        }
        HiloPreprocesamiento emoticones = new HiloPreprocesamiento(5, estadoEmoticones, this);
        emoticones.start();
        while (emoticones.isAlive()) {
        }
        HiloPreprocesamiento caracteresEsp = new HiloPreprocesamiento(6, estadoCaracEsp, this);
        caracteresEsp.start();
        while (caracteresEsp.isAlive()) {
        }
        HiloPreprocesamiento stopWords = new HiloPreprocesamiento(7, estadoStopWord, this);
        stopWords.start();
        while (stopWords.isAlive()) {
        }
        HiloPreprocesamiento palabrasClave = new HiloPreprocesamiento(8, estadoPalClave, this);
        palabrasClave.start();
        while (palabrasClave.isAlive()) {
        }
        HiloPreprocesamiento palabrasCasuales = new HiloPreprocesamiento(9, estadoLenguajeCasual, this);
        palabrasCasuales.start();
        while (palabrasCasuales.isAlive()) {
        }
        HiloPreprocesamiento lematizador = new HiloPreprocesamiento(10, estadoLematizador, this);
        lematizador.start();
        while (lematizador.isAlive()) {
        }
        HiloPreprocesamiento palabrasRaras = new HiloPreprocesamiento(11, estadoPalRara, this);
        palabrasRaras.start();
        while (palabrasRaras.isAlive()) {
        }
        this.controladora.setTweetsClasificar(listaTweetClasificar);
        System.out.println("FIN DEL PROCESAMIENTO");
        this.fin.setText("FIN DEL PREPROCESAMIENTO");
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contCarEsp;
    private javax.swing.JLabel contCasual;
    private javax.swing.JLabel contEmo;
    private javax.swing.JLabel contMencion;
    private javax.swing.JLabel contPalCla;
    private javax.swing.JLabel contPocoFrec;
    private javax.swing.JLabel contUrl;
    private javax.swing.JLabel estadoAcentos;
    private javax.swing.JLabel estadoCaracEsp;
    private javax.swing.JLabel estadoEmoticones;
    private javax.swing.JLabel estadoLematizador;
    private javax.swing.JLabel estadoLenguajeCasual;
    private javax.swing.JLabel estadoLowerCasing;
    private javax.swing.JLabel estadoMenciones;
    private javax.swing.JLabel estadoPalClave;
    private javax.swing.JLabel estadoPalRara;
    private javax.swing.JLabel estadoStopWord;
    private javax.swing.JLabel estadoURL;
    private javax.swing.JLabel fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
